### ISSUE TITLE
The GPCC benchmark

### ISSUE THREAD

**Issue by aprilbian** [arsx958/PCT_PCC#1]
Dear Authors:

  Thanks for this great work! I am following your work and I would like to know the details to implement the benchmark of the GPCC. I noticed that you first scale the point cloud using a 7-bit precision. Did you perform it by first transforming the data points from [-1,1] to [0, 2], then multiply 2^6 to it and finally quantize it to the nearest intergers?

  Moreover, I would also like to know if you use the 'gpcc.py' from PCGv2 to perform the GPCC encode? Is it possible that you provide your implementations for the baseline? Thanks a lot in advance!

Best

**Comment by arsx958** [comment]
Yes, to compare with G-PCC and PCGCv2, we first shift the data points from [-1,1] to [0,2], then multiply by 2 ^ 6, and finally quantify them to the nearest integer.

  We use the code in PCGCv2 to encode the above data, such as 'gpcc. py' and PCGCv2 itself. You should note that after compression, we will rescale the reconstructed point cloud to [-1,1] to prevent the problem of being unable to compare due to different resolutions when calculating PSNR.

**Comment by aprilbian** [comment]
Dear authors:

  Thanks a lot for your reply! I have understand and there is no more issues. Thanks for the good work.
